before_script:
  - export PATH=/opt/plesk/node/7/bin:$PATH
  - npm install --progress false --concurrency=1

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
  only:
    - master
