before_script:
  - export PATH=/opt/plesk/node/7/bin:$PATH
  - /opt/npm-f3-install.sh all --silent

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
  only:
    - master
