# Build
language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
script: npm run build

# Deployment
addons:
  ssh_known_hosts:
  - freiken-douhl.de
before_deploy:
- openssl aes-256-cbc -K $encrypted_1a5c1c8e5976_key -iv $encrypted_1a5c1c8e5976_iv
  -in build/deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -avzr --delete-after $TRAVIS_BUILD_DIR/dist/ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
  on:
    branch: master
